// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Cdataframe
List Cdataframe(List x);
RcppExport SEXP _krisUtils_Cdataframe(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Cdataframe(x));
    return rcpp_result_gen;
END_RCPP
}
// removeNA
NumericVector removeNA(NumericVector a);
RcppExport SEXP _krisUtils_removeNA(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(removeNA(a));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_krisUtils_Cdataframe", (DL_FUNC) &_krisUtils_Cdataframe, 1},
    {"_krisUtils_removeNA", (DL_FUNC) &_krisUtils_removeNA, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_krisUtils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
