# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Cdataframe
#' @description Convert a vector (list) to a data frame.
#' @param x an R vector
#' @usage \dontrun{
#' list <- replicate(250, 1:100, simplify=FALSE)
#' df <- as.Cdataframe(list)
#' }
#' @export
NULL

Cdataframe <- function(x) {
    .Call('_krisUtils_Cdataframe', PACKAGE = 'krisUtils', x)
}

#' @title removeNA
#' @description Remove NA from string or vector.
#' @param a A vector of numerfic values.
#' @usage \dontrun{
#' noNAs <- removeNA(x)
#' 
#' }
#' @export
removeNA <- function(a) {
    .Call('_krisUtils_removeNA', PACKAGE = 'krisUtils', a)
}

