# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title removeNA
#' @description Remove NA from string or vector.
#' @param a A vector of numerfic values.
#' @export
removeNA <- function(a) {
    .Call('krisUtils_removeNA', PACKAGE = 'krisUtils', a)
}

